// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class OsterStadtDb : DataConnection
	{
		public OsterStadtDb()
		{
			InitDataContext();
		}

		public OsterStadtDb(string configuration)
			: base("SQLite", configuration)
		{
			InitDataContext();
		}

		public OsterStadtDb(DataOptions<OsterStadtDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Person> People => this.GetTable<Person>();
	}
}
