// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Person")]
	public class Person
	{
		[Column("Name"     )] public string?  Name      { get; set; } // TEXT
		[Column("Longitude")] public decimal? Longitude { get; set; } // NUMERIC
		[Column("Latitude" )] public decimal? Latitude  { get; set; } // NUMERIC

        public int ClusterId = -1;
        public bool Visited = false;
    }
}
